# Base image
FROM node:20-slim AS base

# Required for build /docs package
ARG OPENAPI_DOCS_URL
ENV OPENAPI_DOCS_URL=${OPENAPI_DOCS_URL}


ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
# FIX: Bad workaround (https://github.com/nodejs/corepack/issues/612)
ENV COREPACK_INTEGRITY_KEYS=0

RUN corepack enable
RUN apt-get update && apt-get install -y iproute2 net-tools ffmpeg

FROM base AS build
COPY . /usr/src/tutoriallm
WORKDIR /usr/src/tutoriallm
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile -r
RUN pnpm run -r --filter=!frontend build

FROM base AS backend-dev
COPY --from=build /usr/src/tutoriallm /usr/src/tutoriallm
WORKDIR /usr/src/tutoriallm/apps/backend
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile --filter=backend
ENV SERVER_PORT=3001
ENV VM_PORT=3002
EXPOSE 3001 3002
CMD [ "pnpm", "dev" ]


FROM base AS frontend-dev
COPY --from=build /usr/src/tutoriallm /usr/src/tutoriallm
WORKDIR /usr/src/tutoriallm/apps/frontend
ARG VITE_BACKEND_URL
ENV VITE_BACKEND_URL=$VITE_BACKEND_URL
ENV PORT=3000
EXPOSE 3000
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile --filter=frontend
CMD ["sh", "-c", "pnpm dev"]
