version: '3.8'

services:
  redis:
  #実稼働ではredis/redis-stack-serverを使用する
    container_name: code-tutorial-redis-dev
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
  db:
    container_name: code-tutorial-db-dev
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: UTC
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${DB_USER} -d ${DB_NAME}'"]
      interval: 5s
      timeout: 60s
      retries: 5
      start_period: 5s  

  app: 
    container_name: code-tutorial-app-dev
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    ports:
      - "$PORT:$PORT"
    env_file:
      - .env
    command: >
      sh -c "
        if [ ! -f /app/.initialized ]; then
          npm install &&
          npm run drizzle:generate &&
          npm run drizzle:push &&
          npm run reset-credential &&
          npm run reset-tutorials &&
          touch /app/.initialized &&
          npm run dev 
        else
          npm install &&
          npm run drizzle:generate &&
          npm run drizzle:push &&
          npm run dev;
        fi
      "
    depends_on:
      db:
        condition: service_healthy
    #開発環境ではホットリロードを使用するため、ボリュームをマウントする
    volumes:
      - /app
      - /app/node_modules

