# ベースイメージとして Node.js 20.14.0 を使用
FROM node:20.14.0

# 必要なパッケージをインストール
RUN apt-get update && apt-get install -y iproute2 net-tools


# 作業ディレクトリを / に設定
WORKDIR /tutorial_app_prod

# package.json と pnpm-lock.yaml を作業ディレクトリにコピー
COPY package.json pnpm-lock.yaml ./

# 依存関係をインストール
RUN npm install -g pnpm && pnpm install

# 全てのファイルを作業ディレクトリにコピー
COPY . .

# ビルドを実行
RUN pnpm exec tsc --nocache && pnpm run build

# ビルド時に使用するポートを設定。envと一致させる
ARG PORT=3000
ARG VM_PORT=3001

ENV PORT=${PORT} \
    # VMのポート
    VM_PORT=${VM_PORT} \
    # シークレット
    NODE_ENV=production

# ポートを公開
EXPOSE ${PORT} ${VM_PORT}

# アプリケーションを実行するコマンド
# チュートリアルと認証情報をリセットする場合は、以下のオプションを追加できます：
# pnpm run reset-credential
# pnpm run reset-tutorials
CMD ["sh", "-c", "pnpm run drizzle:generate && pnpm run drizzle:push && pnpm run start"]
