services:
  jaeger: # telemetry collector
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "16687:16687"
      - "4317:4317"
      - "4318:4318"
      - "9411:9411"
  redis:
  #実稼働ではredis/redis-stack-serverを使用する
    container_name: code-tutorial-redis-dev
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
  db:
    container_name: code-tutorial-db-dev
    image: pgvector/pgvector:pg14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: UTC
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${DB_USER} -d ${DB_NAME}'"]
      interval: 5s
      timeout: 60s
      retries: 5
      start_period: 5s 
    volumes:
      - db_data_db:/var/lib/postgresql/data
  app: 
    container_name: code-tutorial-app-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
      - "3001:3001"
    env_file:
      - .env
    command: >
      sh -c "
        if [ ! -f /app_data/.initialized ]; then
          pnpm install &&
          pnpm run drizzle:generate &&
          pnpm run drizzle:migrate &&
          pnpm run reset-credential &&
          touch /app_data/.initialized &&
          pnpm run dev 
        else
          pnpm install &&
          pnpm run drizzle:generate &&
          pnpm run drizzle:migrate &&
          pnpm run dev;
        fi
      "
    develop:
      watch:
        - action: sync
          path: ./src
          target: /tutorial_app_dev/src
          ignore:
            - node_modules/
        - action: rebuild
          path: ./
          ignore:
            - ./src
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./app_data:/app_data
volumes:
  db_data_db:
