FROM node:20.14.0
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
ENV PORT=3000 \
    DATABASE_HOST="db" \
    DATABASE_USER="postgres" \
    DATABASE_PASSWORD="postgres" \
    DATABASE_NAME="code_tutorial_db"
EXPOSE 3000
CMD ["npm", "run", "dev"]