FROM node:20.14.0
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build
ENV PORT=80 \
    DATABASE_HOST="db" \
    DATABASE_USER="postgres" \
    DATABASE_PASSWORD="postgres" \
    DATABASE_NAME="code_tutorial_db"\
    NODE_ENV=production
EXPOSE 80
CMD ["npm", "start"]