# ベースイメージとして Node.js 20.14.0 を使用
FROM node:20.14.0

# 必要なパッケージをインストール
RUN apt-get update && apt-get install -y iproute2 net-tools ffmpeg


# 作業ディレクトリを / に設定
WORKDIR /tutorial_app_dev

# package.json と pnpm-lock.yaml を作業ディレクトリにコピー
COPY package.json pnpm-lock.yaml ./

# 依存関係をインストール
RUN npm install -g pnpm && pnpm install

# 全てのファイルを作業ディレクトリにコピー
COPY . .

# 環境変数を設定
ENV PORT=3000
#バックエンドようのポートが必要だよ！
ENV VM_PORT=3001

ENV PORT=${PORT} \
    # VMのポート
    VM_PORT=${VM_PORT}
    
# ポート3000を公開
EXPOSE 3000

# アプリケーションを実行するコマンド
# チュートリアルと認証情報をリセットする場合は、以下のオプションを追加できます：
# pnpm run reset-credential
# pnpm run reset-tutorials
CMD ["pnpm", "run", "dev"]
