version: '3.8'

services:
  app:
    container_name: code-tutorial-app
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    env_file:
      - .env
    command: npm run start