version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: frontend-dev
    volumes:
      - ./apps/frontend:/usr/src/tutoriallm/apps/frontend
      - /pnpm/store:/pnpm/store
    command: pnpm dev
    environment:
      - VITE_BACKEND_URL=http://localhost:3001
    ports:
      - "3000:3000"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: backend-dev
    volumes:
      - ./apps/backend:/usr/src/tutoriallm/apps/backend
      - ./app_data:/app_data
      - /pnpm/store:/pnpm/store
    command: pnpm dev
    environment:
      NODE_ENV: development
