FROM node:20.14.0

# Set the working directory to 
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy all files from the backend directory to the working directory
COPY . .
RUN npm run build

ARG PORT=8080
ENV PORT=${PORT} \
    #シークレット
    NODE_ENV=production

# Expose the port
EXPOSE ${PORT}

# Command to run the application
# If you need to reset tutorial and credential, you can add the following options when its start.:
# npm run reset-credential
# npm run reset-tutorials
CMD ["sh", "-c", "npm run drizzle:generate && npm run drizzle:push && npm run start"]