version: '3.8'

services:
  redis:
    container_name: code-tutorial-redis-prod
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"
  db:
    container_name: code-tutorial-db-prod
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: UTC
  app: 
    container_name: code-tutorial-app-prod
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    ports:
      - $PORT:$PORT
    env_file:
      - .env
    command: >
      sh -c "npm install &&
             npm run drizzle:generate &&
             npm run drizzle:push &&
             npm run start"    
    depends_on:
      - db
    environment:
      - PORT=$PORT
      - DB_HOST=db
