packages:
 - 'apps/*'
 - 'packages/*'
catalog:
  better-auth: 1.1.19
  blockly: 11.2.2
  dotenv: 16.4.7
  hono: 4.7.7
  rfc6902: 5.1.2
  tsx: 4.19.3
  js-yaml: 4.1.0
  zod: 3.24.3
  tailwindcss: 3.4.17
  "@types/node": 20.17.30
  typescript: 5.8.3
