packages:
 - 'apps/*'
 - 'packages/*'
catalog:
  better-auth: ^1.1.10
  blockly: ^11.1.1
  dotenv: ^16.4.5
  drizzle-kit: ^0.30.1
  drizzle-orm: ^0.38.2
  hono: ^4.6.5
  rfc6902: ^5.1.1
  tsx: ^4.19.2
  zod: ^3.24.1
  "@types/node": ^20.16.12
  typescript: ^5.6.3

