packages:
 - 'apps/*'
 - 'packages/*'
catalog:
  better-auth: 1.1.19
  vite: 6.0.2
  blockly: 11.2.2
  dotenv: 16.5.0
  hono: 4.8.3
  rfc6902: 5.1.2
  tsx: 4.20.3
  js-yaml: 4.1.0
  zod: 3.25.67
  tailwindcss: 3.4.17
  "@types/node": 20.19.2
  typescript: 5.8.3
