FROM node:20.14.0

# Set the working directory to /app
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy all files from the backend directory to the working directory
COPY . .

# Set environment variable
ENV PORT=3000

# Expose the port 3000
EXPOSE 3000

# Command to run the application
# If you need to reset tutorial and credential, you can add the following options when its start.:
# If you need to reset tutorial and credential, you can add the following options when its start.:
# npm run reset-credential
# npm run reset-tutorials
CMD ["npm", "run", "dev"]