FROM node:20.14.0

# Set the working directory to /app
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy all files from the backend directory to the working directory
COPY . .
RUN npm run build
ENV PORT=${PORT} \
    #シークレット
    NODE_ENV=production

# Expose the port 3000
EXPOSE ${PORT}

# Command to run the application
CMD ["npm", "run", "start"]