name: Code quality of app

on:
  push:
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest
      - name: Install dependencies
        run: |
          pnpm pkg delete scripts.postinstall
          pnpm install --frozen-lockfile

      - name: Run Biome
        run: biome ci .
